var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__57ddaa87._.js")
R.c("server/chunks/ssr/Desktop_E-Commerce-App-Admin-Panel-UI-Design_client_ddb45fbd._.js")
R.c("server/chunks/ssr/5baea_next_dist_esm_build_templates_app-page_93c53784.js")
R.c("server/chunks/ssr/[root-of-the-server]__78a3af9b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__58824bbb._.js")
R.c("server/chunks/ssr/5baea_next_dist_1666bd43._.js")
R.c("server/chunks/ssr/Desktop_E-Commerce-App-Admin-Panel-UI-Design_client_src_app_476c2dd5._.js")
R.c("server/chunks/ssr/2f4ca__pnpm_a9182097._.js")
R.c("server/chunks/ssr/[root-of-the-server]__074031df._.js")
R.c("server/chunks/ssr/5baea_next_dist_client_components_1bc96186._.js")
R.c("server/chunks/ssr/5baea_next_dist_client_components_builtin_forbidden_30c775e1.js")
R.c("server/chunks/ssr/be596_client__next-internal_server_app__not-found_page_actions_b98e32bb.js")
R.m(68366)
module.exports=R.m(68366).exports
